### ISSUE TITLE
Missing static file or hidden feature in mashlib config?

### ISSUE THREAD

**Issue by renyuneyun** [solid/community-server-recipes#12]
I'm learning how to extend CSS with custom components, and am reading the configurations file for mashlib recipe. 
There is this part in the file, which I assume would serve the specified file (`assets_value`) to the specified target (`assets_key`).

```
        {
          "StaticAssetHandler:_assets_key": "/.well-known/solid/login",
          "StaticAssetHandler:_assets_value": "./node_modules/solid-auth-client/dist-popup/popup.html"
        },
```

However, I could not find this file under the `node_modules` directory, and this module is not a dependency specified in `package.json`.

Therefore, is this some hidden features that I'm not aware of, or is this a legacy thing that is simply ignored (by `StaticAssetHandler`, I assume)?

By the way, the login page does not seem to be different compared to that without mashlib, even after adding the dependency. Is this expected? (I.e. this does not affect the login page, but something else?)

**Comment by joachimvh** [comment]
> Therefore, is this some hidden features that I'm not aware of, or is this a legacy thing that is simply ignored (by `StaticAssetHandler`, I assume)?

@RubenVerborgh should confirm but I'm going to guess that that is indeed a legacy reference that can probably be removed.

> By the way, the login page does not seem to be different compared to that without mashlib, even after adding the dependency. Is this expected? (I.e. this does not affect the login page, but something else?)

This is expected. If the server returns an HTML resource it is going to be returned as-is. Same if you go to the registration page for example, see some related discussion at #6

**Comment by renyuneyun** [comment]
Thanks @joachimvh . That discussion there helps me clarify a few things :)

**Comment by RubenVerborgh** [comment]
Thanks for finding this, @renyuneyun. It's indeed legacy from when Mashlib was still using `solid-auth-client`.
