### ISSUE TITLE
Penny config: How can I create a new pod?

### ISSUE THREAD

**Issue by joeitu** [solid/community-server-recipes#2]
Hello, 

I got a bit surprise by penny recipe behavior, and by the fact that I couldn't find a way to create a new account.

## Steps
Launch penny config as explained in README.md
Start browser to the recipe address. In our case `http://localhost:3000`

## Current behavior
Show penny pod browser.
reached to `localhost:3000/idp/register` return an error

## Expected

Being able to see the default CSS index page, with link to the sign-up page.
Being able to access the sign-up page, through an url ( ideally `/idp/register` )
Having penny interface only when accessing a pod url, like `localhost:3000/mypodname/`

**Comment by RubenVerborgh** [comment]
> > Good catch! but I still don't get what I would expect:
> 
> Haha woops, that's not good indeed. I will check up on that.

That has now been fixed by https://github.com/solid/community-server/pull/1035
