### ISSUE TITLE
Penny: Clicking "Your profile" after login redirect to a broken page

### ISSUE THREAD

**Issue by joeitu** [solid/community-server-recipes#4]
## step to reproduce

1. start a recipe instance with:
`npx community-solid-server -c config-penny.json -f ~/Documents/` -p 3005

2. go to `localhost:3005/idp/register/` and create a new account, choose the option " Create a new WebID for my Pod." and fill up the form, choose `bar` as a pod name

3. after registration, the "You've been signed up" page shows a link to the Pod URL `localhost:3005/bar/` , click the URL 

4. Now you should be back on Penny UI, click the `Connect` button and enter your freshly created credential ( you might encounter #3 but don't mind)

5.  clicking the "Your profile" button on the top right corner return an error: 

## expected

See some profile page

## actual behaviour

redirect to `http://localhost:3005/bar/profile/card/#http%3A%2F%2Flocalhost%3A3005%2Fbar%2Fprofile%2Fcard%23me`

with  "This Resource does not exist."

![fig_2](https://user-images.githubusercontent.com/60817856/145384610-7fe1a45d-ec98-4c74-bf85-2afc6ba74009.jpg)

## potential solution

Maybe the "Your profile" link should to `http://localhost:3005/bar/profile/` instead ? 
Is it penny that is built around solidcommunity.net's pod, which fills up `profile/card/` with data contrary to SCS that leave `profile/card/` empty that cause the bug?

**Comment by RubenVerborgh** [comment]
I think this is a Penny bug, could you report it to @Vinnl via https://gitlab.com/vincenttunru/penny?

**Comment by Vinnl** [comment]
Unfortunately this seems to be caused by the framework Penny is using automatically appending a trailing slash, with the only other option being automatic _removal_ of trailing slashes (breaking the viewing of Containers): https://github.com/vercel/next.js/discussions/23988

Tracking this for Penny here: https://gitlab.com/vincenttunru/penny/-/issues/17
