### ISSUE TITLE
Penny: Broken logo on "Disconnect" button

### ISSUE THREAD

**Issue by joeitu** [solid/community-server-recipes#5]
Penny's "Connect" button correctly show Solid's logo.

![image](https://user-images.githubusercontent.com/60817856/145569601-c8c74a9f-c0dc-4268-b268-3e97c32cf808.png)

But, after a login, the Disconnect button show a broken logo. 

![image](https://user-images.githubusercontent.com/60817856/145569873-cab7a100-0275-4204-aa6c-41e316b42e90.png)

### solution 1
Add a new `StaticAssetHandler in config-penny.json
```json
   "comment": "Serve Penny static files.",
      "@id": "urn:solid-server:default:StaticAssetHandler",
      "@type": "StaticAssetHandler",
      "assets": [
        {
          "StaticAssetHandler:_assets_key": "/server-ui/",
          "StaticAssetHandler:_assets_value": "./node_modules/penny-pod-inspector/server-ui/"
        },
        {
          "StaticAssetHandler:_assets_key": "/solid-emblem.svg",
          "StaticAssetHandler:_assets_value": "./node_modules/penny-pod-inspector/public/solid-emblem.svg"
        }

      ]
```

### solution 2

Change penny's code to use `src="/server-ui/solid-emblem.svg"` ( like the connect button ) instead of `src="/solid-emblem.svg"`

Which solution should be preferred?

**Comment by RubenVerborgh** [comment]
I think Solution 2, so a fix in https://gitlab.com/vincenttunru/penny

**Comment by joeitu** [comment]
fixed https://gitlab.com/vincenttunru/penny/-/merge_requests/7#note_786009060
