### ISSUE TITLE
Update for CSS 3.0

### ISSUE THREAD

**Issue by renyuneyun** [solid/community-server-recipes#7]
CSS 3.0 was released recently, while this repository is not updated with it.

I tried manually updating some elements (e.g. `component.json` and `config-mashlib.json`), but starting the server still results in errors:
```
Could not build the config files from /root/community-server-recipes/mashlib/config-mashlib.json
Cause: Error while parsing file "/root/community-server-recipes/mashlib/node_modules/@solid/community-server-metadata-extender/dist/PassthroughDataAccessor.jsonld": Failed to load remote context https://linkedsoftwaredependencies.org/bundles/npm/@solid/community-server/^2.0.0/components/context.jsonld: Not Found
Error: Error while parsing file "/root/community-server-recipes/mashlib/node_modules/@solid/community-server-metadata-extender/dist/PassthroughDataAccessor.jsonld": Failed to load remote context https://linkedsoftwaredependencies.org/bundles/npm/@solid/community-server/^2.0.0/components/context.jsonld: Not Found
```

I presume this is because some recursive dependency using CSS 2.0 -- [community-server-metadata-extender](https://github.com/RubenVerborgh/solid-metadata-extender) in this case.

I'm not sure if I'm doing it correctly. So hope this repo can be updated with CSS 3.0 : )

**Comment by RubenVerborgh** [comment]
All done in #8!
